schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "HumGen3D"
version = "4.0.19"
name = "Human Generator"
tagline = "Create photorealistic characters"
maintainer = "Oliver J. Post & Alexander Lashko humgen3d.com"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://help.humgen3d.com"



blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = ["windows-x64", "macos-arm64", "macos-x86", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
   "./wheels/pillow-10.4.0-cp311-cp311-macosx_10_10_x86_64.whl",
   "./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
   "./wheels/pillow-10.4.0-cp311-cp311-manylinux_2_28_x86_64.whl",
   "./wheels/pillow-10.4.0-cp311-cp311-win_amd64.whl"
]

[permissions]
#network = "Need to sync motion-capture data to server"
files = "Interacting with the Human Generator asset files"
# clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
 [build]
 paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/*.zip",
 ]